### ISSUE TITLE
Custom Reference Genome and GTF file

### ISSUE THREAD

**Issue by ky66** [CCBR/Pipeliner#471]
So, I am using a bacterial reference genome and in the pipeliner UI for normal RNA-seq, there is no option for custom genomes. How would you go about customizing the pipeliner to work with a different genome and annotation?

Thanks

**Comment by skchronicles** [comment]
Hey @ky66, thank you for reaching out to us. I just have a few quick questions.

How did you generate the indices and reference files for this custom reference genome? Did you use PIM (https://github.com/CCBR/PIM)? If so, I can briefly meet with you over Teams when you have some free time to show you how to add a new reference genome.

Please let me know what you think.

Best,
@skchronicles

**Comment by ky66** [comment]
So sorry did not see your response. I have a custom fasta file ... a meeting would be super helpful. My email is kamyar.yazdani@nih.gov. I really appreciate your help.

Thanks,
Kamyar

**Comment by skchronicles** [comment]
Hey @ky66, 

I saw your new issue related to PIM in https://github.com/CCBR/Pipeliner/issues/473. 

For full continuity, I have closed that issue so we can continue the discussion here. I think the issue maybe due to providing a non-standard GTF file, but we can troubleshoot the problem in a meeting. 

Please let me know when you have some free time this week, and I can setup a meeting with you. You can reply back to my DM on MS Teams. If you have any other questions, please let me know. 

Best,
@skchronicles
